name: Feature Request
description: Have an awesome idea? Let's do this!
assignees:
  - hizumiaoba
labels:
  - enhancement
  - investigating
body:
  - type: markdown
    attributes:
      value: |
        Thanks for providing us your fantastic idea! Keep in mind this is not a place for discussion.
        
        If it's a bit abstract, you can head to [Project Discussions](https://github.com/CheeredAdventure/ReverseCraft-Reimagined/discussions/new/choose)!
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see added to the mod?
      placeholder: Describe your feature idea in detail
    validations:
      required: true
  - type: textarea
    id: problem-solution
    attributes:
      label: Problem and Solution
      description: What problem does this feature solve? How would it benefit users?
      placeholder: Explain why this feature is needed and how it improves the mod
    validations:
      required: true
  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: Do you have any specific ideas about how this feature could be implemented? (Optional)
      placeholder: Share your thoughts on how this could be added to the mod
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important do you think this feature is?
      options:
        - Low (Would be nice to have)
        - Medium (Would improve the mod significantly)
        - High (Critical for gameplay)
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information, screenshots, or examples to help explain your feature request
      placeholder: Add any other context, references, or screenshots about the feature request here
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have checked that this feature has not already been requested
          required: true
        - label: I understand this is a feature request and not a bug report
          required: true
