name: Take snapshot of the current main branch
on:
  push:
    branches:
      - main
    paths:
      - '**.java'
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Take snapshot
        run: ./gradlew snapshot
      - name: Upload snapshot to action summary
        uses: actions/upload-artifact@v4
        with:
          name: snapshot
          path: build/libs/*.jar
