name: snapshot.yaml
on:
  push:
    branches:
      - main
    branches-ignore:
      - 'release/**/*'
    tags-ignore:
      - 'v*'
  workflow_dispatch:


jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Take snapshot with Gradle
        run: ./gradlew snapshot
      - name: Upload snapshot
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.ref }} snapshot"
          path: build/libs/*.jar
